Portal/CPC.Web/Models/HomeViewModels.cs
using System;
using System.Web;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CPC.Web.Models
{
    public class HomeViewModels
    {    
        public ICollection<NewsViewModel> NewsModels { get; set; }

        [Required]
        [Display(Name = "帳號")]
        public string Account { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "密碼")]
        public string Password { get; set; }

        [Display(Name = "記住我?")]
        public bool RememberMe { get; set; }

    }
    public class NewsViewModel
    {
        public string Title { get; set; }
        public string Content { get; set; }
        public string PublishDate { get; set; }

    }


}

Portal/CPC.Web/Controllers/HomeController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using CPC.Web.Models;
using NLog;
using System.Web.Security;
using CPC.Web.Repository.Interface;
using CPC.Web.Repository;
using CPC.DataModel;
using System.Collections.Generic;

namespace CPC.Web.Controllers
{
    public class HomeController : Controller
    {
        private static Logger logger = NLog.LogManager.GetCurrentClassLogger();

        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public HomeController()
        {
        }

        public HomeController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ActionResult Index(string returnUrl)
        {
            INewsRepository newsRepo = new NewsRepository();
            //logger.Info("GET: /Home/Index" + news.GetAllNews().Count());
            CPCUser model = new CPCUser();
            HomeViewModels viewModels = new HomeViewModels();
            //logger.Info("-->" + newsRepo.GetAllNewsBySql().Count());
            viewModels.Account = User.Identity.Name;
            List<NewsViewModel> list = new List<NewsViewModel>();
            foreach (CPC_NEWS news in newsRepo.GetAllNews())
            {
                NewsViewModel newsModel = new NewsViewModel();
                newsModel.Title = news.TITLE;
                newsModel.Content = news.CONTENT;
                TaiwanCalendar taiwanCalendar = new TaiwanCalendar();

                newsModel.PublishDate = string.Format("民國 {0} 年 {1} 月 {2} 日", taiwanCalendar.GetYear(news.PUBLISH_DATE.Value),
                news.PUBLISH_DATE.Value.Month,
                news.PUBLISH_DATE.Value.Day);
                list.Add(newsModel);
            }
            viewModels.NewsModels = list;
            logger.Info("GET: /Home/Index");
            ViewBag.ReturnUrl = returnUrl;
            return View(viewModels);
        }

        public ActionResult About()
        {
            logger.Info("Info");
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        // GET: /Home/Login
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            logger.Info("GET: /Home/Login");
            ViewBag.ReturnUrl = returnUrl;
            return View("Index");
        }

        // POST: /Home/Login
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(CPCUser model, string returnUrl)
        {
            logger.Info("POST: /Home/Login " + ModelState.IsValid);
            logger.Info("POST: /Home/Login returnUrl:" + returnUrl);

            if (!ModelState.IsValid)
            {
                //logger.Info("RedirectToAction: Statistics Index");
                //return RedirectToAction("Index", "Statistics", model);
                return View(model);
            }


            // 這不會計算為帳戶鎖定的登入失敗
            // 若要啟用密碼失敗來觸發帳戶鎖定，請變更為 shouldLockout: true
            //var result = await SignInManager.PasswordSignInAsync(model.Account, model.Password, model.RememberMe, shouldLockout: false);
            var result = SignInStatus.Failure;
            if (IsValid(model))
            {
                FormsAuthentication.RedirectFromLoginPage(model.Account, false);
                if (returnUrl == null)
                {
                    returnUrl = Url.Content("~/Statistics");
                }

                //FormsAuthentication.SetAuthCookie(model.Account, false);
                result = SignInStatus.Success;
            }
            else
            {
                result = SignInStatus.Failure;
            }
            switch (result)
            {
                case SignInStatus.Success:
                    return RedirectToLocal(returnUrl);
                case SignInStatus.LockedOut:
                    return View("Lockout");
                case SignInStatus.RequiresVerification:
                    return RedirectToAction("SendCode", new { ReturnUrl = returnUrl, RememberMe = model.RememberMe });
                case SignInStatus.Failure:
                default:
                    ModelState.AddModelError("", "登入嘗試失試。");
                    return View("Index", model);
                    //return View(model);
            }
        }

        // <summary>
        /// 登出
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        [HttpPost]
        public ActionResult Logout()
        {
            logger.Info("POST: /Home/Logout");
            FormsAuthentication.SignOut();//登出
            return RedirectToAction("Login", "Home");

        }

        private bool IsValid(CPCUser user)
        {
            return (user.Account == "test" && user.Password == "test");
        }


        #region Helper
        // 新增外部登入時用來當做 XSRF 保護
        private const string XsrfKey = "XsrfId";

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }

        internal class ChallengeResult : HttpUnauthorizedResult
        {
            public ChallengeResult(string provider, string redirectUri)
                : this(provider, redirectUri, null)
            {
            }

            public ChallengeResult(string provider, string redirectUri, string userId)
            {
                LoginProvider = provider;
                RedirectUri = redirectUri;
                UserId = userId;
            }

            public string LoginProvider { get; set; }
            public string RedirectUri { get; set; }
            public string UserId { get; set; }

            public override void ExecuteResult(ControllerContext context)
            {
                var properties = new AuthenticationProperties { RedirectUri = RedirectUri };
                if (UserId != null)
                {
                    properties.Dictionary[XsrfKey] = UserId;
                }
                context.HttpContext.GetOwinContext().Authentication.Challenge(properties, LoginProvider);
            }
        }
        #endregion
    }


}

Portal/CPC.Web/Controllers/StationController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using CPC.Web.Models;
using NLog;

namespace CPC.Web.Controllers
{
    public class StationController : Controller
    {
        private static Logger logger = NLog.LogManager.GetCurrentClassLogger();

        // GET: /Station/index
        public ActionResult Index()
        {
            logger.Info("GET: /Station/Index");
            return View();
        }
    }
}

Portal/CPC.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Portal/CPC.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Portal/CPC.Web/Views/Home/Index.cshtml
@using CPC.Web.Models
@model HomeViewModels
@{
    ViewBag.Title = "首頁";
}

<div class="main-content">


    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-9 col-lg-9">
                <div class="row">
                    <div class="col-xl-4 col-lg-4">
                        <div class="panel">
                            <img class="home-item-image" src="@Url.Content("~/Images/station.png")" />
                            <div class="home-item-desc home-item-desc-green">
                                @Html.ActionLink("加油點查詢", "Index", "Station")
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4 col-lg-4">
                        <div class="panel">
                            <img class="home-item-image" src="@Url.Content("~/Images/apply.png")" />
                            <div class="home-item-desc home-item-desc-green">
                                車隊卡申辦資訊
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4 col-lg-4">
                        <div class="panel">
                            <img class="home-item-image" src="@Url.Content("~/Images/advantage.png")" />
                            <div class="home-item-desc home-item-desc-green">
                                車隊卡好處多
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xl-12 col-lg-12">
                        <div class="panel">
                            <div class="ribbon-wrap">
                                <div class="ribbon">會員專區</div>
                            </div>
                            @using (Html.BeginForm("Login", "Home", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                            {
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary(true, "", new { @class = "text-danger", @style= " position: relative;left: 60px;" })
                                <div class="station-query form-group" style="display: flex;justify-content: space-between">
                                    <div class="form-inline" style="padding-left: 30px">
                                        <label for="account">帳號：</label>
                                        @Html.TextBoxFor(m => m.Account, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.Account, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-inline">
                                        <label for="password">密碼：</label>
                                        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-inline">
                                        <label for="code">驗證碼：</label>
                                        <img src="~/Images/image-code.gif">
                                        <input type="password" id="code" class="form-control" size="10" />
                                    </div>
                                    <div class="form-inline">
                                        <input type="submit" value="登入" class="btn btn-default" />
                                        <input type="reset" name="reset" class="btn" value="清除">
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-3">
                <div class="panel">
                    <div class="ribbon-wrap">
                        <div class="ribbon">最新消息</div>
                    </div>
                    <table class="table" style="margin-top: 45px">
                        <tbody>
                            @foreach (var item in Model.NewsModels)
                            {
                                <tr>
                                    <th scope="row"><i class="iChart chart--dodgerBlue"></i></th>
                                    <td>
                                        <div style="text-align: left">
                                            @Html.DisplayFor(modelItem => item.PublishDate)
                                        </div>
                                        <div style="text-align: left;">
                                            @Html.DisplayFor(modelItem => item.Title)
                                        </div>
                                    </td>
                                </tr>
                            }
                           
                            <tr>
                                <th scope="row"></th>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>
                </div>

            </div>

        </div>

    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}